vim.o.breakindent = true
-- vim.o.clipboard = 'unnamedplus'
vim.o.colorcolumn = '80'
vim.o.completeopt = 'menuone,noselect'
vim.o.guicursor = ''
vim.o.hlsearch = false
vim.o.ignorecase = true
vim.o.incsearch = true
vim.o.mouse = 'a'
vim.o.number = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.relativenumber = true
vim.o.scrolloff = 8
vim.o.signcolumn = 'yes'
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.swapfile = false
vim.o.termguicolors = true
vim.o.timeoutlen = 300
vim.o.undodir = os.getenv('HOME') .. '/.vim/undodir'
vim.o.undofile = true
vim.o.updatetime = 50
vim.o.wrap = false
vim.wo.number = true
vim.wo.signcolumn = 'yes'
